version: '3.8'
# docker compose -f docker-compose.redis.yml up -d
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
